//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BioNetModel.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=MRBIN;Initial Catalog=Bio;User ID=sa;Password=123456;Encrypt=False;Tr" +
            "ustServerCertificate=True")]
        public string BioConnectionString {
            get {
                return ((string)(this["BioConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=MRBIN\\;Initial Catalog=Bio;User ID=sa;Password=123456")]
        public string BioConnectionString1 {
            get {
                return ((string)(this["BioConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=118.70.117.242;Initial Catalog=Bio;User ID=sa;Encrypt=False;TrustServ" +
            "erCertificate=True")]
        public string BioConnectionString2 {
            get {
                return ((string)(this["BioConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=MRBIN;Initial Catalog=Bio;User ID=sa;Encrypt=False;TrustServerCertifi" +
            "cate=True")]
        public string BioConnectionString3 {
            get {
                return ((string)(this["BioConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=118.70.117.242;Initial Catalog=Bio;User ID=sa")]
        public string BioConnectionString4 {
            get {
                return ((string)(this["BioConnectionString4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=118.70.117.242;Initial Catalog=Bio;Persist Security Info=True;User ID" +
            "=sa")]
        public string BioConnectionString5 {
            get {
                return ((string)(this["BioConnectionString5"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=MRBIN\\;Initial Catalog=Bio;User ID=sa")]
        public string BioConnectionString6 {
            get {
                return ((string)(this["BioConnectionString6"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=MRBIN\\;Initial Catalog=Bio;Persist Security Info=True;User ID=sa")]
        public string BioConnectionString7 {
            get {
                return ((string)(this["BioConnectionString7"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=MRBIN\\;Initial Catalog=Bio;Persist Security Info=True;User ID=sa;Pass" +
            "word=123456")]
        public string BioConnectionString8 {
            get {
                return ((string)(this["BioConnectionString8"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=POWERSOFT02\\SQLEXPRESS;Initial Catalog=Bio;User ID=sa")]
        public string BioConnectionString9 {
            get {
                return ((string)(this["BioConnectionString9"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=POWERSOFT02\\SQLEXPRESS;Initial Catalog=Bio;User ID=sa;Password=031352" +
            "9521")]
        public string BioConnectionString10 {
            get {
                return ((string)(this["BioConnectionString10"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=POWERSOFT02\\SQLEXPRESS;Initial Catalog=Bio_TestSync;Integrated Securi" +
            "ty=True")]
        public string BioConnectionString11 {
            get {
                return ((string)(this["BioConnectionString11"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=POWERSOFT02\\SQLEXPRESS;Initial Catalog=Bio_TestSync_Test;Integrated S" +
            "ecurity=True")]
        public string Bio_TestSync_TestConnectionString {
            get {
                return ((string)(this["Bio_TestSync_TestConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=BIONET_LETHANHQ\\SQLEXPRESS;Initial Catalog=Bio_TestSync;User ID=sa;Pa" +
            "ssword=bionetvietnam;Encrypt=False;TrustServerCertificate=True")]
        public string Bio_TestSyncConnectionString {
            get {
                return ((string)(this["Bio_TestSyncConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=BIONET_LETHANHQ\\SQLEXPRESS;Initial Catalog=Bio_TestSync;Integrated Se" +
            "curity=True")]
        public string Bio_TestSyncConnectionString1 {
            get {
                return ((string)(this["Bio_TestSyncConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=BIONET_LETHANHQ\\SQLEXPRESS;Initial Catalog=Bio_TestSync_Cu;Integrated" +
            " Security=True")]
        public string Bio_TestSync_CuConnectionString {
            get {
                return ((string)(this["Bio_TestSync_CuConnectionString"]));
            }
        }
    }
}
